---
- name: Configuração do Zabbix no servidor local
  hosts: localhost
  become: true
  roles:
    - python_dependencies
    - system_dependencies
    - zabbix_install
    - database_setup
    - services_setup

