---
- name: Baixar e instalar coleções Ansible no servidor offline
  hosts: localhost
  become: yes
  tasks:
    - name: Baixar o arquivo de coleções do repositório
      get_url:
        url: "http://10.196.182.20/repo/ansible/zabbix-collection.tar"
        dest: "/tmp/zabbix-collection.tar"

    - name: Criar diretório para extração das coleções
      file:
        path: "/tmp/zabbix-collections"
        state: directory
        mode: '0755'

    - name: Extrair as coleções
      ansible.builtin.unarchive:
        src: "/tmp/zabbix-collection.tar"
        dest: "/tmp/zabbix-collections"
        remote_src: yes

    - name: Instalar as coleções extraídas (modo offline)
      shell: |
        for collection in /tmp/zabbix-collections/*.tar.gz; do
          ansible-galaxy collection install $collection --offline
        done
      args:
        executable: /bin/bash

    - name: Confirmar instalação das coleções
      command: ansible-galaxy collection list
      register: result

    - name: Exibir coleções instaladas
      debug:
        msg: "{{ result.stdout_lines }}"

