---
# Instalar MySQL Server
- name: Instalar o MySQL Server
  dnf:
    name: mysql-server
    state: present

# Iniciar e habilitar o serviço MySQL
- name: Iniciar e habilitar o serviço MySQL
  systemd:
    name: mysqld
    state: started
    enabled: yes

# Criar banco de dados Zabbix
- name: Criar banco de dados Zabbix
  community.mysql.mysql_db:
    name: zabbix
    state: present
    encoding: utf8mb4
    collation: utf8mb4_bin

# Criar usuário do banco de dados Zabbix
- name: Criar usuário do banco de dados Zabbix
  community.mysql.mysql_user:
    name: zabbix
    password: "password"
    priv: "zabbix.*:ALL"
    host: localhost
    state: present

- name: Configurar log_bin_trust_function_creators
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 1

- name: Importar esquema inicial para o banco de dados Zabbix
  shell: >
    zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz |
    mysql --default-character-set=utf8mb4 -uzabbix -ppassword zabbix
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Desativar log_bin_trust_function_creators
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 0

